name: Django CI

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.6.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.6.8

#    - name: Install Dependencies
#      run: |
#        sudo apt install -y ansible
#        ansible-galaxy collection install -r bootstrap/development/requirements.yml
#
#    - name: Configure main.yml
#      run: |
#        cp bootstrap/development/main.copyme main.yml
#        sed -e 's/^db_admin_passwd:.*/db_admin_passwd: root/' \
#             -e 's/^redis_passwd:.*/redis_passwd: root/' \
#             -e 's/^from_email:.*/from_email: hamzak@berkeley.edu/' \
#             -e 's/^admin_email:.*/admin_email: hamzak@berkeley.edu/' \
#             -e 's/^request_approval_cc_list:.*/request_approval_cc_list: ["hamzak@berkeley.edu"]/' -i main.yml
#
#    - name: Run Ansible Playbook
#      run: |
#        ansible-playbook bootstrap/development/playbook.yml

    - name: Install Dependencies
      run: |
        sudo apt -y install apache2-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Settings Files From Samples And Create Log Files
      run: |
        sudo mkdir -p /var/log/user_portals/cf_mybrc
        sudo chmod 775 /var/log/user_portals/cf_mybrc
        
        sudo touch /var/log/user_portals/cf_mybrc/cf_mybrc_portal.log
        sudo chmod 666 /var/log/user_portals/cf_mybrc/cf_mybrc_portal.log
        
        sudo touch /var/log/user_portals/cf_mybrc/cf_mybrc_api.log
        sudo chmod 666 /var/log/user_portals/cf_mybrc/cf_mybrc_api.log
        
        sudo chown -R :www-data /var/log/user_portals/cf_mybrc

        cp coldfront/config/local_strings.py.sample coldfront/config/local_strings.py
        cp coldfront/config/local_settings.py.sample coldfront/config/local_settings.py
        
    - name: Run Tests
      run: |
        python manage.py test
