name: Django CI

on:
  schedule:
    - cron: '0 10 * * *' # 10 AM UTC = 3 AM PST
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:9.6.24
        env:
          POSTGRES_DB: cf_brc_db
          POSTGRES_PASSWORD: test
          POSTGRES_PORT: 5432
          POSTGRES_USER: test
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.6.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.6.8

    - name: Cache apache2-dev
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
          packages: apache2-dev

    - name: Cache Python packages
      id: cache-python
      uses: actions/cache@v3
      with:
        path: ~/venv
        key: ${{ runner.os }}-python-packages-${{ hashFiles('requirements.txt') }}

    - if: ${{ steps.cache-python.outputs.cache-hit != 'true' }}
      name: Install Python packages
      run: |
        python3.6 -m venv ~/venv
        source ~/venv/bin/activate
        pip install -r requirements.txt
        
#    - if: ${{ steps.cache-apache2-dev.outputs.cache-hit != 'true' }}
#      name: Install apache2-dev
#      run: |
#        sudo apt -y install apache2-dev
        
    - name: Create Settings Files From Samples And Create Log Files
      run: |
        sudo mkdir -p /var/log/user_portals/cf_mybrc
        sudo chmod 775 /var/log/user_portals/cf_mybrc
        
        sudo touch /var/log/user_portals/cf_mybrc/cf_mybrc_portal.log
        sudo chmod 666 /var/log/user_portals/cf_mybrc/cf_mybrc_portal.log
        
        sudo touch /var/log/user_portals/cf_mybrc/cf_mybrc_api.log
        sudo chmod 666 /var/log/user_portals/cf_mybrc/cf_mybrc_api.log
        
        sudo chown -R :www-data /var/log/user_portals/cf_mybrc

        cp coldfront/config/local_strings.py.sample coldfront/config/local_strings.py
        cp coldfront/config/local_settings.py.sample coldfront/config/local_settings.py
        cp coldfront/config/test_settings.py.sample coldfront/config/test_settings.py
        
    - name: Run Tests
      run: |
        source ~/venv/bin/activate
        python manage.py migrate
        python manage.py test coldfront.core.utils.tests.test_export_data
