name: Django CI

on:
  schedule:
    - cron: '0 10 * * *' # 10 AM UTC = 3 AM PST
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:9.6.24
        env:
          POSTGRES_DB: cf_brc_db
          POSTGRES_PASSWORD: test
          POSTGRES_PORT: 5432
          POSTGRES_USER: test
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.6.8
      uses: actions/setup-python@v3
      with:
        python-version: 3.6.8

    - name: Install Dependencies
      run: |
        sudo apt -y install apache2-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create Settings Files From Samples And Create Log Files
      run: |
        sudo mkdir -p /var/log/user_portals/cf_mybrc
        sudo chmod 775 /var/log/user_portals/cf_mybrc
        
        sudo touch /var/log/user_portals/cf_mybrc/cf_mybrc_portal.log
        sudo chmod 666 /var/log/user_portals/cf_mybrc/cf_mybrc_portal.log
        
        sudo touch /var/log/user_portals/cf_mybrc/cf_mybrc_api.log
        sudo chmod 666 /var/log/user_portals/cf_mybrc/cf_mybrc_api.log
        
        sudo chown -R :www-data /var/log/user_portals/cf_mybrc

        cp coldfront/config/local_strings.py.sample coldfront/config/local_strings.py
        cp coldfront/config/local_settings.py.sample coldfront/config/local_settings.py
        cp coldfront/config/test_settings.py.sample coldfront/config/test_settings.py
        
    - name: Run Tests
      run: |
        python manage.py migrate
        #python manage.py test
